"""Add category and group to role_attributes, drop description

Revision ID: 966d244d4548
Revises: 9b1ff8233832
Create Date: 2025-12-31 11:21:36.405225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966d244d4548'
down_revision: Union[str, None] = '9b1ff8233832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_attributes', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('role_attributes', sa.Column('group', sa.String(length=100), nullable=True))
    op.drop_column('role_attributes', 'description')
    op.create_index(op.f('ix_role_attributes_category'), 'role_attributes', ['category'], unique=False)
    op.create_index(op.f('ix_role_attributes_group'), 'role_attributes', ['group'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_role_attributes_group'), table_name='role_attributes')
    op.drop_index(op.f('ix_role_attributes_category'), table_name='role_attributes')
    op.drop_column('role_attributes', 'group')
    op.drop_column('role_attributes', 'category')
    op.add_column('role_attributes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###